version: '3'
services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
      - /storages/django-notes-media/:/app/media
    depends_on:
      - db
      - migrations
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5435:5435"
    command:
      - "postgres"
      - "-c"
      - "port=5435"
    env_file:
      - .env
    restart: always

  migrations:
    build:
      context: .
    command: [ "python", "manage.py", "migrate", "--no-input" ]
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./:/app